---
# Builds the static site via pnpm, then copies that local directory's contents
# to Firebase, at: https://praxwallet.com
name: Deploy Prax marketing site
on:
  # Support ad-hoc runs via dispatch, so we can deploy from
  # unmerged feature branches if necessary.
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    # The build step takes a lot of CPU, so we'll bump up to 8 vCPUs.
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install npm dependencies
        run: pnpm install

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Build static site
        run: pnpm build

      - name: Deploy dapp static site to firebase
        # N.B. the firebase-action helper doesn't support semver, e.g. `@v13`,
        # so we hardcode a version.
        uses: w9jds/firebase-action@v13.7.2
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
