# Uploads extension dist to chrome dev dashboard when a release is made in github.
# Admins can log into https://chrome.google.com/webstore/devconsole to submit for approval.
# Note: `maniftest.json` should already be updated to the desired version before release.

# Prod: https://chrome.google.com/webstore/detail/penumbra-wallet/lkpmkhpnhknhmibgnmmhdhgdilepfghe
# Beta: https://chrome.google.com/webstore/detail/penumbra-wallet/ejpfkiblcablembkdhcofhokccbbppnc
name: Upload extension

on:
  push:
    tags:
      - '*-?v[0-9]+*'
  workflow_call:
  workflow_dispatch:

env:
  DO_NOT_TRACK: 1

jobs:
  publish:
    environment: ext-publish
    name: Release Prax wallet
    runs-on: buildjet-16vcpu-ubuntu-2204

    steps:
      - uses: actions/checkout@v4
      - id: built
        uses: buildjet/cache@v4
        with:
          path: .turbo
          key: ${{ hashFiles('pnpm-lock.yaml') }}-${{ github.ref }}-${{ github.sha }}-publish
          restore-keys: ${{ hashFiles('pnpm-lock.yaml') }}-${{ github.ref }}-${{ github.sha }}-test
      - uses: pnpm/action-setup@v4
      - uses: buildjet/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - name: Bundle Prax wallet BETA with development mode
        env:
          NODE_ENV: development
        run: |
          pnpm -C apps/extension bundle:beta
          (cd apps/extension/beta-dist && zip -r $GITHUB_WORKSPACE/beta.zip .)

      - name: Bundle Prax wallet with production mode
        env:
          NODE_ENV: production
        run: |
          pnpm -C apps/extension bundle:prod
          (cd apps/extension/dist && zip -r $GITHUB_WORKSPACE/prod.zip .)

      - name: Draft Prax wallet BETA GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Prax wallet BETA
          draft: true
          prerelease: true
          body: |
            Prax wallet BETA ${{ github.ref_name }} as uploaded to the Chrome Web Store.
          files: |
            beta.zip:Prax.wallet.BETA.${{ github.ref_name }}.crx

      - name: Draft Prax wallet GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Prax wallet
          draft: true
          prerelease: false
          body: |
            Prax wallet ${{ github.ref_name }} as uploaded to the Chrome Web Store.
          files: |
            prod.zip:Prax.wallet.${{ github.ref_name }}.crx

      - name: Upload Prax wallet BETA to Chrome Web Store
        uses: penumbra-zone/chrome-extension-upload@v1
        with:
          file-path: beta.zip
          extension-id: ejpfkiblcablembkdhcofhokccbbppnc
          client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          publish: false

      - name: Upload Prax wallet to Chrome Web Store
        uses: penumbra-zone/chrome-extension-upload@v1
        with:
          file-path: prod.zip
          extension-id: lkpmkhpnhknhmibgnmmhdhgdilepfghe
          client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          publish: false
